apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-volume-claim
  namespace: laurens
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual # Use EBS in template
