apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-volume
  namespace: laurens
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Use EBS in template
