# Seems like we cannot define services in the deployment manifest?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbench-deployment
  namespace: laurens
  labels:
    app: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench
        image: "jupyter/minimal-notebook"
        ports:
        - containerPort: 8888
          name: http
        env:
          # Using the configmap
          - name: TEST_CONFIGMAP
            valueFrom:
              configMapKeyRef:
                name: demo-configmap
                key: foo
          # Using the secret
          # NOTE: Will we still create the secrets directly?
          - name: TEST_SECRET
            valueFrom:
              secretKeyRef:
                name: demo-secret
                key: password
      restartPolicy: Always
      volumes:
        # NOTE: How are these managed?
        # NOTE: Why volume mounts AND PVCs?
        - name: demo-volume
          persistentVolumeClaim:
            claimName: demo-volume-claim